<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>$(RevitTargetFramework)</TargetFramework><UseWPF>true</UseWPF><CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies></PropertyGroup><Import Project="../../build/RevitReferences.props"/><ItemGroup><ProjectReference Include="../BimPortfolio.Revit/BimPortfolio.Revit.csproj"/><ProjectReference Include="../BimPortfolio.UI/BimPortfolio.UI.csproj"/></ItemGroup></Project>
