'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PORTFOLIO_PLAYWRIGHT_MODULE||'playwright');
(async()=>{
  const input=path.resolve(process.argv[2]||'demo-output/AccessRoute.html');
  const output=path.resolve(process.argv[3]||'artifacts/report-preview');
  fs.mkdirSync(output,{recursive:true});
  const browser=await chromium.launch({headless:true,...(process.env.PORTFOLIO_CHROMIUM?{executablePath:process.env.PORTFOLIO_CHROMIUM}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1050}});
  page.setDefaultTimeout(10000);
  const errors=[],remoteRequests=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>{if(/^https?:/.test(request.url()))remoteRequests.push(request.url());});
  try{
    await page.goto(pathToFileURL(input).href);
    const expected=await page.locator('#report-data').evaluate(element=>JSON.parse(element.textContent));
    assert.equal(await page.locator('#routes tr').count(),expected.Plan.Routes.length);
    assert.equal(await page.locator('#diagram .tray').count(),expected.Graph.Edges.length);
    const successful=expected.Plan.Routes.filter(r=>r.Status==='OK'||r.Status==='CableLimitExceeded');
    assert.equal(await page.locator('#diagram .route').count(),successful.length);
    await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
    const first=successful[0];
    await page.getByLabel('Поиск устройств').fill(first.Mark);
    assert.equal(await page.locator('#routes tr').count(),1);
    await page.locator('#routes tr').click();
    assert.equal(await page.locator('#diagram .route').count(),1);
    assert.ok((await page.locator('#detail').textContent()).includes(first.DeviceUniqueId));
    const planPoints=await page.locator('#diagram .route').getAttribute('points');
    await page.getByLabel('Проекция').selectOption('xz');
    const sectionPoints=await page.locator('#diagram .route').getAttribute('points');
    assert.notEqual(planPoints,sectionPoints);
    await page.getByRole('button',{name:'Все маршруты'}).click();
    assert.equal(await page.locator('#diagram .route').count(),successful.length);
    await page.getByLabel('Поиск устройств').fill('no-such-device');
    assert.equal(await page.locator('#routes tr').count(),0);
    assert.equal(await page.locator('#empty').isVisible(),true);
    await page.getByLabel('Поиск устройств').fill('');
    await page.getByLabel('Проекция').selectOption('xy');
    assert.equal(await page.locator('#audit tr').count(),expected.Issues.length);
    await page.setViewportSize({width:390,height:844});
    const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);
    assert.equal(overflow,false,'Mobile report must not overflow horizontally');
    await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
    assert.deepEqual(errors,[]);
    assert.deepEqual(remoteRequests,[],'Standalone report must not require network');
    fs.writeFileSync(path.join(output,'browser-check.json'),JSON.stringify({CheckedUtc:new Date().toISOString(),Browser:await browser.version(),Routes:expected.Plan.Routes.length,SuccessfulPaths:successful.length,AuditIssues:expected.Issues.length,Checks:['render','route selection','search','projection switch','empty state','mobile layout','no JS errors','no external requests'],Passed:true},null,2));
    console.log('Browser checks passed; desktop/mobile screenshots saved in '+output);
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
